name: Deploy to Fly

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
        working-directory: ./server
      - name: Run tests
        run: npm run test
        working-directory: ./server

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build-and-test
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: Development - Fly
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Development - Fly
        run: flyctl deploy -c ./server/fly-dev.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DEV }}