name: Deploy to Fly
on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy proxy to Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./server/fly-dev.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DEV }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy proxy to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./server/fly-prod.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PROD }}
