name: Deploy to Fly
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: Development - Fly
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Production - Fly
        run: flyctl deploy -c fly-prod.toml
        working-directory: ./server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DEV }}